---
# Validate if controller is up and running
- name: Avi Controller | CSP | Validate controller service
  uri:
    url: 'https://{{ con_csp_mgmt_ip }}/#!/login'
    validate_certs: no
  retries: 120
  delay: 30
  register: task_result
  until: task_result.status == 200
  ignore_errors: yes
  delegate_to: localhost
